const legal={
  privacy:`<div class="legal-document"><h2>Informativa privacy</h2><p><b>Ultimo aggiornamento:</b> 23 luglio 2026</p><p class="legal-missing"><b>Dati obbligatori mancanti:</b> prima della pubblicazione il titolare deve inserire denominazione o nome, indirizzo e un contatto privacy. Meteo AI non può inventare questi dati.</p><h3>1. Titolare e contatti</h3><p>Titolare del trattamento: <b>[DA INSERIRE]</b><br>Indirizzo: <b>[DA INSERIRE]</b><br>Email privacy: <b>[DA INSERIRE]</b><br>Responsabile della protezione dei dati, se nominato: <b>[DA INSERIRE O “NON NOMINATO”]</b></p><h3>2. Dati e finalità</h3><ul><li><b>Preferenze locali:</b> tema, località, preferiti, cache, sorveglianze e presa visione dell’informativa sono salvati nel browser per fornire le funzioni richieste.</li><li><b>Posizione:</b> viene letta solo dopo il consenso del dispositivo e usata per cercare previsioni, eventi e punti marini vicini.</li><li><b>Notifiche:</b> vengono abilitate solo su richiesta e controllate mentre la pagina o la PWA è attiva.</li><li><b>Dati tecnici di rete:</b> quando il browser contatta hosting e fornitori esterni, questi possono ricevere indirizzo IP, data/ora e dati tecnici necessari alla connessione secondo le proprie informative.</li></ul><h3>3. Servizi esterni</h3><p>Il sito è ospitato su Vercel e interroga Open-Meteo, OpenStreetMap/Nominatim, USGS, NASA EONET, NOAA/Tsunami.gov, JMA e BMKG. Carica inoltre risorse tecniche da Google Fonts e unpkg.</p><h3>4. Base giuridica e conservazione</h3><p>Le preferenze tecniche sono trattate per erogare il servizio richiesto. Geolocalizzazione e notifiche dipendono dal consenso espresso nel browser, revocabile dalle impostazioni del dispositivo. Le informazioni locali restano fino alla cancellazione dei dati del sito; le cache hanno durate tecniche indicate nell’app.</p><h3>5. Destinatari, trasferimenti e diritti</h3><p>I fornitori esterni agiscono secondo i propri ruoli e informative e possono operare fuori dallo Spazio Economico Europeo. Il titolare deve verificare ruoli, basi di trasferimento e condizioni prima della pubblicazione. L’utente può cancellare i dati locali dalle impostazioni del browser e, una volta inseriti i contatti del titolare, esercitare i diritti previsti dagli articoli 15–22 GDPR o proporre reclamo al Garante.</p></div>`,
  cookies:`<div class="legal-document"><h2>Cookie e memoria locale</h2><p><b>Ultimo aggiornamento:</b> 23 luglio 2026</p><h3>Uso attuale</h3><p>Meteo AI non installa cookie pubblicitari, di profilazione o analytics. Utilizza localStorage, sessionStorage, Cache Storage e il service worker esclusivamente per funzioni richieste dall’utente e prestazioni tecniche.</p><h3>Informazioni memorizzate</h3><ul><li>tema e località selezionata;</li><li>preferiti e regole del radar personale;</li><li>cache temporanee di previsioni, confini ed eventi;</li><li>presa visione di questa informativa;</li><li>file dell’interfaccia necessari alla modalità PWA e offline.</li></ul><h3>Come cancellare</h3><p>È possibile rimuovere tutto cancellando i dati del sito dalle impostazioni del browser o disinstallando la PWA. La cancellazione rimuove preferiti, cache e impostazioni. Se in futuro saranno aggiunti analytics, pubblicità o contenuti incorporati non tecnici, questa informativa e il meccanismo di consenso dovranno essere aggiornati prima dell’attivazione.</p></div>`,
  terms:`<div class="legal-document"><h2>Termini e limitazioni d’uso</h2><p><b>Ultimo aggiornamento:</b> 23 luglio 2026</p><h3>Servizio informativo</h3><p>Meteo AI aggrega dati modellistici e fonti pubbliche e applica regole automatiche nel browser. Non utilizza un modello generativo e non garantisce completezza, continuità o accuratezza delle previsioni.</p><h3>Emergenze e avvisi</h3><p>Gli avvisi Meteo AI non sono allerte ufficiali. Per pericoli, evacuazioni e decisioni di sicurezza fanno fede esclusivamente protezione civile, autorità locali e fonti ufficiali.</p><h3>Mare e navigazione</h3><p>Indici marini, punti costieri e confronto fra porti sono esplorativi. La linea visualizzata è geometrica, può attraversare terra o aree non navigabili e non considera fondali, ostacoli, traffico, ordinanze, capacità dell’imbarcazione o rotte ufficiali. Non usare il sito per navigare o prendere decisioni di sicurezza in mare.</p><h3>Eventi naturali e attività professionali</h3><p>Mondo Live descrive eventi osservati e livelli pubblicati dalle fonti; non prevede terremoti o eruzioni. Profili per droni, agricoltura, edilizia e altre attività non sostituiscono normativa, valutazioni professionali, manuali operativi o controlli sul posto.</p><h3>Servizi di terzi</h3><p>Disponibilità, licenze e condizioni dei fornitori esterni restano di competenza dei rispettivi gestori. Prima di un uso commerciale il titolare deve verificare condizioni, attribuzioni, limiti di traffico e idoneità dell’hosting.</p></div>`
};

$$('[data-legal]').forEach(button=>{
  button.onclick=()=>{
    $('#legalContent').innerHTML=legal[button.dataset.legal];
    $('#legalModal').showModal();
  };
});
$$('[data-dialog-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());
$('#dismissPrivacy').onclick=()=>{
  localStorage.setItem('meteo-privacy-seen','1');
  $('#cookieBanner').classList.add('hidden');
};
if(localStorage.getItem('meteo-privacy-seen'))$('#cookieBanner').classList.add('hidden');
