function initMap(){map=L.map('map',{zoomControl:true}).setView([lastPlace.latitude,lastPlace.longitude],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);marker=L.marker([lastPlace.latitude,lastPlace.longitude]).addTo(map)}
async function searchPlaces(q){const r=await fetchResilient(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=6&language=it&format=json`);return (await r.json()).results||[]}
function placeLabel(place){return `${place.name}${place.admin1&&place.admin1!==place.name?', '+place.admin1:''}${place.country?', '+place.country:''}`}
function locationSlug(value){return String(value||'area').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'area'}
function locationSeoPath(place){const id=Number(place?.id);if(!Number.isFinite(id)||!place?.country_code)return'';return `/meteo/${String(place.country_code).toLowerCase()}/${locationSlug(place.admin1)}/${locationSlug(place.name)}-${id}`}
function syncLocationSeo(place,replace=false){const path=locationSeoPath(place);if(!path)return;const absolute=`${location.origin}${path}`;(replace?history.replaceState:history.pushState).call(history,{meteoPlace:place},'',path);document.title=`Meteo ${place.name} oggi e previsioni 14 giorni | Meteo AI`;const description=`Meteo ${place.name}: temperatura, pioggia, vento e previsioni fino a 14 giorni per ${place.admin1||place.country||'la località selezionata'}.`;const descriptionTag=document.querySelector('meta[name="description"]');if(descriptionTag)descriptionTag.content=description;const canonical=document.querySelector('link[rel="canonical"]');if(canonical)canonical.href=absolute;const ogUrl=document.querySelector('meta[property="og:url"]');if(ogUrl)ogUrl.content=absolute}
function selectWeatherPlace(place){try{localStorage.setItem('meteo-location-mode','manual')}catch(_){}syncLocationSeo(place);loadWeather(place)}
async function loadWeather(place){lastPlace=place;try{localStorage.setItem('meteo-current-place',JSON.stringify(place))}catch(_){}lastMarine=null;marineAutoPending=false;marineAutoFailed=false;professionalData=null;professionalLoading=false;professionalPlaceKey=`${Number(place.latitude).toFixed(3)}-${Number(place.longitude).toFixed(3)}`;resetMarine();resetProbability();resetHistoryComparison();syncSeaAtlas(place);const label=placeLabel(place);$('#locationName').textContent=label;$('#activeLocationName').textContent=label;$('#updatedAt').textContent='Aggiornamento in corso...';
 const params=new URLSearchParams({latitude:place.latitude,longitude:place.longitude,timezone:'auto',forecast_days:14,current:'temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,visibility',hourly:'temperature_2m,precipitation_probability,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m,uv_index',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,uv_index_max,sunrise,sunset,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant'});
 const cacheKey=`meteo-cache-v2-${Number(place.latitude).toFixed(3)}-${Number(place.longitude).toFixed(3)}`;try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<600000){lastData=cached.weather;render(lastData);if(cached.air)renderAir(cached.air);loadHistoricalWeather({silent:true});map.setView([place.latitude,place.longitude],10);marker.setLatLng([place.latitude,place.longitude]).bindPopup(place.name).openPopup();return}}catch(_){}
 try{const [r,airResponse]=await Promise.all([fetchResilient(`https://api.open-meteo.com/v1/forecast?${params}`),fetchResilient(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${place.latitude}&longitude=${place.longitude}&current=european_aqi,pm10,pm2_5`)]);if(!r.ok)throw Error(`Previsioni ${r.status}`);lastData=await r.json();const air=airResponse.ok?await airResponse.json():null;render(lastData);if(air)renderAir(air);loadHistoricalWeather({silent:true});try{sessionStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),weather:lastData,air}))}catch(_){}map.setView([place.latitude,place.longitude],10);marker.setLatLng([place.latitude,place.longitude]).bindPopup(place.name).openPopup();}catch(e){toast(e.name==='AbortError'?'Il servizio meteo non ha risposto in tempo':'Dati meteo momentaneamente non disponibili');$('#updatedAt').textContent=e.name==='AbortError'?'Connessione scaduta • riprova':'Aggiornamento non disponibile • riprova più tardi';}}
function render(d){const c=d.current,day=d.daily,w=weather(c.weather_code);$('#currentTemp').textContent=Math.round(c.temperature_2m);$('#weatherIcon').innerHTML=iconHTML(c.weather_code,'large');$('#weatherLabel').textContent=w[0];$('#feelsLike').textContent=`Percepita ${Math.round(c.apparent_temperature)}°`;$('#todayMax').textContent=Math.round(day.temperature_2m_max[0])+'°';$('#todayMin').textContent=Math.round(day.temperature_2m_min[0])+'°';$('#humidity').textContent=c.relative_humidity_2m+'%';$('#wind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('#pressure').textContent=Math.round(c.surface_pressure)+' hPa';$('#visibility').textContent=(c.visibility/1000).toFixed(1)+' km';$('#precip').textContent=c.precipitation+' mm';$('#uv').textContent=day.uv_index_max[0].toFixed(1);$('#updatedAt').textContent=`Aggiornato alle ${new Date(c.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})} • ${d.timezone_abbreviation}`;setAtmosphere(c.weather_code,c.time);renderHourly(d);renderDaily(d);renderNextTwoDays(d);renderAI(d);renderExtras(d);renderWeatherWindow(d);renderWind(d);renderConfidence(d);renderAlerts(d);renderSpecialProfile();autoLoadMarine()}
function setAtmosphere(code,time){document.body.classList.remove('weather-clear','weather-cloud','weather-rain','is-night');document.body.classList.add(code===0?'weather-clear':code<=3?'weather-cloud':'weather-rain');const h=new Date(time).getHours();if(h<6||h>19)document.body.classList.add('is-night')}
function renderAir(d){const a=Math.round(d.current.european_aqi||0),labels=a<=20?'Ottima':a<=40?'Buona':a<=60?'Discreta':a<=80?'Scarsa':a<=100?'Molto scarsa':'Estremamente scarsa';$('#aqi').textContent=a;$('#aqiLabel').textContent=labels;$('#aqiMeter').style.marginLeft=Math.min(96,a/120*100)+'%'}
function renderExtras(d){const rise=new Date(d.daily.sunrise[0]),set=new Date(d.daily.sunset[0]);$('#sunrise').textContent=rise.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});$('#sunset').textContent=set.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});$('#daylight').textContent=((set-rise)/36e5).toFixed(1)+' ore di luce';const rain=d.daily.precipitation_probability_max[0],uv=d.daily.uv_index_max[0],wind=d.current.wind_speed_10m;const items=[['Passeggiata',rain<35],['Sport all’aperto',rain<30&&uv<8&&wind<35],['Bucato',rain<20],['Mare / escursioni',rain<25&&wind<25]];$('#activities').innerHTML=items.map(x=>`<div class="activity"><span>${x[0]}</span><b class="${x[1]?'good':'warn'}">${x[1]?'Consigliata':'Prudenza'}</b></div>`).join('')}
const aiActivities={walk:{name:'passeggiata',hours:[7,21],temp:[12,27],rain:35,wind:30},run:{name:'corsa',hours:[6,21],temp:[8,22],rain:25,wind:28},bike:{name:'bicicletta',hours:[7,20],temp:[10,26],rain:18,wind:22},beach:{name:'mare',hours:[9,19],temp:[23,35],rain:12,wind:20},laundry:{name:'bucato',hours:[8,18],temp:[14,36],rain:8,wind:28},event:{name:'evento all’aperto',hours:[10,22],temp:[15,28],rain:15,wind:24}};let selectedActivity='walk';
function renderWeatherWindow(d){const rule=aiActivities[selectedActivity],h=d.hourly,now=new Date(),start=Math.max(0,h.time.findIndex(t=>new Date(t)>=now)),end=Math.min(h.time.length,start+168),candidates=[];for(let i=start;i<end-2;i++){const dates=h.time.slice(i,i+3).map(t=>new Date(t)),hour=dates[0].getHours();if(hour<rule.hours[0]||hour+2>rule.hours[1]||dates[0].getDate()!==dates[2].getDate())continue;const avg=a=>a.slice(i,i+3).reduce((s,v)=>s+(Number(v)||0),0)/3,temp=avg(h.temperature_2m),rain=avg(h.precipitation_probability),wind=avg(h.wind_speed_10m),uv=avg(h.uv_index),bad=h.weather_code.slice(i,i+3).some(c=>c>=80);let score=100-rain*.65-Math.max(0,wind-rule.wind)*2.2-(bad?28:0);if(temp<rule.temp[0])score-=(rule.temp[0]-temp)*4;if(temp>rule.temp[1])score-=(temp-rule.temp[1])*4;if(selectedActivity!=='beach'&&uv>7)score-=(uv-7)*3;score=Math.max(0,Math.min(100,Math.round(score)));candidates.push({i,date:dates[0],end:dates[2],temp,rain,wind,score})}const chosen=[];candidates.sort((a,b)=>b.score-a.score).forEach(c=>{if(chosen.length<3&&!chosen.some(x=>Math.abs(x.i-c.i)<6))chosen.push(c)});if(chosen[0])chosen[0].best=true;chosen.sort((a,b)=>a.date-b.date);if(!chosen.length)return $('#windowResult').innerHTML='<div class="window-loading">Nessuna finestra adatta trovata nei prossimi 7 giorni.</div>';$('#windowResult').innerHTML=chosen.map(c=>{const day=c.date.toLocaleDateString('it-IT',{weekday:'short',day:'numeric',month:'short'}),times=`${c.date.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}–${new Date(c.end.getTime()+36e5).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`,reason=c.rain<10?`Quasi asciutto, ${Math.round(c.temp)}°`:`Pioggia ${Math.round(c.rain)}%, ${Math.round(c.temp)}°`;return `<article class="window-card ${c.best?'best':''}"><span>${c.best?'Migliore scelta':day}</span><b>${day} • ${times}</b><p>${reason}, vento ${Math.round(c.wind)} km/h.</p><div class="window-score"><i style="--score:${c.score}%"></i><strong>${c.score}/100</strong></div></article>`}).join('')}
function renderHourly(d){const now=new Date(),start=Math.max(0,d.hourly.time.findIndex(t=>new Date(t)>=now));$('#hourly').innerHTML=d.hourly.time.slice(start,start+12).map((t,i)=>{const idx=start+i;return `<div class="hour ${i===0?'now':''}"><span>${i===0?'Adesso':new Date(t).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><i>${iconHTML(d.hourly.weather_code[idx])}</i><b>${Math.round(d.hourly.temperature_2m[idx])}°</b><span>Pioggia ${d.hourly.precipitation_probability[idx]}%</span></div>`}).join('')}
function val(c){return unit==='c'?Math.round(c):Math.round(c*9/5+32)}
function reliabilityForDay(i){return i<=2?['Alta','high']:i<=6?['Buona','medium']:['Indicativa','low']}
function renderDaily(d){$('#daily').innerHTML=d.daily.time.map((t,i)=>{const confidence=reliabilityForDay(i);return `<div class="day ${i===0?'today':''}"><b>${i===0?'Oggi':new Date(t+'T12:00').toLocaleDateString('it-IT',{weekday:'short'})}</b><small>${new Date(t+'T12:00').toLocaleDateString('it-IT',{day:'numeric',month:'short'})}</small><i>${iconHTML(d.daily.weather_code[i])}</i><div class="temps"><b>${val(d.daily.temperature_2m_max[i])}°</b><span>${val(d.daily.temperature_2m_min[i])}°</span></div><div class="rain">Pioggia ${d.daily.precipitation_probability_max[i]}%</div><span class="confidence-badge ${confidence[1]}">${confidence[0]}</span></div>`}).join('')}
function renderNextTwoDays(d){const target=$('#nextTwoDays');if(!target)return;target.innerHTML=[1,2].map((i,index)=>{const date=new Date(d.daily.time[i]+'T12:00'),label=index===0?'Domani':date.toLocaleDateString('it-IT',{weekday:'long'}),condition=weather(d.daily.weather_code[i])[0];return `<div class="next-day-mini"><div><span>${label}</span><small>${date.toLocaleDateString('it-IT',{day:'numeric',month:'short'})}</small></div><i>${iconHTML(d.daily.weather_code[i])}</i><div class="next-day-condition"><b>${condition}</b><small>Pioggia ${d.daily.precipitation_probability_max[i]}%</small></div><div class="next-day-temps"><b>${val(d.daily.temperature_2m_max[i])}°</b><span>${val(d.daily.temperature_2m_min[i])}°</span></div></div>`}).join('')}
function renderConfidence(d){const volatile=d.daily.weather_code.slice(0,3).some(c=>c>=80),rain=Math.max(...d.daily.precipitation_probability_max.slice(0,3));$('#confidenceNow').textContent=volatile||rain>=70?'Buona':'Alta';$('#confidenceWeek').textContent='Buona';$('#confidenceLong').textContent='Indicativa'}

function renderAlerts(d){
 const days=d.daily,alerts=[],maxRain=Math.max(...days.precipitation_probability_max.slice(0,3)),maxGust=Math.max(...days.wind_gusts_10m_max.slice(0,3)),maxTemp=Math.max(...days.temperature_2m_max.slice(0,3)),minTemp=Math.min(...days.temperature_2m_min.slice(0,3)),maxUv=Math.max(...days.uv_index_max.slice(0,3)),storm=days.weather_code.slice(0,3).some(code=>code>=95);
 if(storm)alerts.push(['danger','Temporali possibili','Uno o più giorni mostrano condizioni temporalesche: controlla gli aggiornamenti e gli avvisi ufficiali.']);
 if(maxGust>=55)alerts.push(['danger','Raffiche forti',`Raffiche previste fino a ${Math.round(maxGust)} km/h nei prossimi tre giorni.`]);else if(maxGust>=40)alerts.push(['warning','Vento da monitorare',`Possibili raffiche fino a ${Math.round(maxGust)} km/h.`]);
 if(maxRain>=75)alerts.push(['warning','Elevato rischio di pioggia',`Probabilità giornaliera fino al ${Math.round(maxRain)}%.`]);
 if(maxTemp>=35)alerts.push(['danger','Caldo intenso',`Massime previste fino a ${Math.round(maxTemp)}°: limita l’esposizione nelle ore centrali.`]);else if(minTemp<=-2)alerts.push(['warning','Gelo possibile',`Minime previste fino a ${Math.round(minTemp)}°.`]);
 if(maxUv>=8)alerts.push(['warning','UV molto elevato',`Indice UV fino a ${maxUv.toFixed(1)}: protezione e ombra sono raccomandate.`]);
 const wave=Number(lastMarine?.current?.wave_height);if(Number.isFinite(wave)&&wave>=1.5)alerts.push([wave>=2.5?'danger':'warning','Mare impegnativo',`Nel punto marino analizzato le onde raggiungono ${wave.toFixed(1)} m.`]);
 if(!alerts.length)alerts.push(['neutral','Nessuna criticità evidente','I principali indicatori previsionali non superano le soglie di attenzione nei prossimi tre giorni.']);
 $('#alertsList').innerHTML=alerts.map(([level,title,copy])=>`<div class="alert-item ${level}"><i>${level==='danger'?'!':level==='warning'?'△':'✓'}</i><div><b>${title}</b><p>${copy}</p></div></div>`).join('');
}

const specialProfileRules={
 fishing:{name:'Pesca',marine:true},sailing:{name:'Vela',marine:true},surf:{name:'Surf',marine:true},children:{name:'Bambini'},pets:{name:'Animali'},drones:{name:'Droni'},agriculture:{name:'Agricoltura',professional:true},construction:{name:'Edilizia',professional:true},hiking:{name:'Escursionismo',professional:true},photography:{name:'Fotografia',professional:true}
};
function renderSpecialProfile(){
 if(!lastData)return;const rule=specialProfileRules[selectedSpecialProfile];if(rule.professional&&!professionalData){$('#profileScore').textContent='…';$('#profileName').textContent=rule.name.toUpperCase();$('#profileStatus').textContent=professionalLoading?'Analisi professionale in corso':'Preparo gli indicatori professionali';$('#profileAdvice').textContent='Carico su richiesta suolo, copertura nuvolosa, visibilità, evapotraspirazione e durata delle precipitazioni.';$('#profileFactors').innerHTML='<span><b>OTTIMIZZAZIONE</b>Una sola richiesta, cache 30 minuti</span>';ensureProfessionalData();return}if(rule.professional&&professionalData?.error){$('#profileScore').textContent='--';$('#profileName').textContent=rule.name.toUpperCase();$('#profileStatus').textContent='Dati non disponibili';$('#profileAdvice').textContent='Gli indicatori professionali non sono raggiungibili in questo momento. I dati meteo generali restano disponibili.';$('#profileFactors').innerHTML='<button id="professionalRetry">Riprova analisi professionale</button>';$('#professionalRetry').onclick=()=>{professionalData=null;ensureProfessionalData()};return}const d=lastData,c=d.current,day=d.daily,wind=Number(c.wind_speed_10m||0),gust=Number(c.wind_gusts_10m||0),rain=Number(day.precipitation_probability_max[0]||0),uv=Number(day.uv_index_max[0]||0),temp=Number(c.temperature_2m||0),visibility=Number(c.visibility||0)/1000,wave=Number(lastMarine?.current?.wave_height),period=Number(lastMarine?.current?.wave_period),factors=[];let score=100,advice='';
 const add=(label,value,tone='good')=>factors.push(`<span class="${tone}"><b>${label}</b>${value}</span>`);
 if(selectedSpecialProfile==='fishing'){score-=rain*.35+Math.max(0,wind-18)*2+Math.max(0,gust-30)*1.2;add('Pioggia',`${Math.round(rain)}%`,rain<35?'good':'warn');add('Vento',`${Math.round(wind)} km/h`,wind<22?'good':'warn');if(Number.isFinite(wave)){score-=wave*18;add('Onde',`${wave.toFixed(1)} m`,wave<1?'good':'warn');advice=wave<1&&wind<22?'Condizioni interessanti, con mare e vento relativamente gestibili.':'Scegli un punto riparato e verifica i bollettini locali.'}}
 if(selectedSpecialProfile==='sailing'){score-=Math.abs(wind-18)*1.7+Math.max(0,gust-38)*2+rain*.25;if(Number.isFinite(wave)){score-=Math.max(0,wave-1.3)*24;add('Onde',`${wave.toFixed(1)} m`,wave<1.5?'good':'warn')}add('Vento',`${Math.round(wind)} km/h`,wind>=10&&wind<=28?'good':'warn');add('Raffiche',`${Math.round(gust)} km/h`,gust<38?'good':'warn');advice=wind>=10&&wind<=28&&gust<38?'Vento utile e raffiche sotto la soglia scelta dal profilo.':'Condizioni poco equilibrate: esperienza e tipo di imbarcazione fanno la differenza.'}
 if(selectedSpecialProfile==='surf'){score-=Math.max(0,wind-28)*2+rain*.15;if(Number.isFinite(wave)){score-=wave<.6?(0.6-wave)*70:wave>2.5?(wave-2.5)*35:0;score-=Number.isFinite(period)&&period<5?(5-period)*8:0;add('Onde',`${wave.toFixed(1)} m`,wave>=.6&&wave<=2.5?'good':'warn');add('Periodo',Number.isFinite(period)?`${period.toFixed(1)} s`:'n/d',period>=5?'good':'warn')}add('Vento',`${Math.round(wind)} km/h`,wind<28?'good':'warn');advice=Number.isFinite(wave)&&wave>=.6&&wave<=2.5?'Moto ondoso compatibile con il profilo, da valutare in base al proprio livello.':'Il profilo non trova una combinazione ideale di onde, periodo e vento.'}
 if(selectedSpecialProfile==='children'){score-=rain*.45+Math.max(0,wind-24)*2+Math.max(0,uv-6)*7+Math.max(0,16-temp)*4+Math.max(0,temp-28)*5;add('Temperatura',`${Math.round(temp)}°`,temp>=16&&temp<=28?'good':'warn');add('UV',uv.toFixed(1),uv<6?'good':'warn');add('Pioggia',`${Math.round(rain)}%`,rain<30?'good':'warn');advice=uv>=6?'Meglio ombra, protezione solare e pause frequenti.':'Condizioni valutate per gioco e spostamenti all’aperto, con supervisione adulta.'}
 if(selectedSpecialProfile==='pets'){score-=rain*.3+Math.max(0,wind-30)*1.5+Math.max(0,8-temp)*4+Math.max(0,temp-27)*7;add('Temperatura',`${Math.round(temp)}°`,temp>=8&&temp<=27?'good':'warn');add('Pioggia',`${Math.round(rain)}%`,rain<35?'good':'warn');add('Vento',`${Math.round(wind)} km/h`,wind<30?'good':'warn');advice=temp>=29?'Evita asfalto caldo e ore centrali; acqua e ombra sono essenziali.':'Buona base per passeggiate, adattando durata, razza, età e salute dell’animale.'}
 if(selectedSpecialProfile==='drones'){score-=rain*.9+Math.max(0,wind-20)*3+Math.max(0,gust-28)*2+(visibility<5?25:0);add('Vento',`${Math.round(wind)} km/h`,wind<20?'good':'warn');add('Raffiche',`${Math.round(gust)} km/h`,gust<28?'good':'warn');add('Visibilità',`${visibility.toFixed(1)} km`,visibility>=5?'good':'warn');advice=rain<15&&wind<20&&gust<28?'Condizioni meteorologiche favorevoli; restano obbligatori regole, area e limiti del drone.':'Pioggia, vento o visibilità rendono prudente rimandare il volo.'}
 if(selectedSpecialProfile==='agriculture'){const p=professionalData,h=p.hourly,start=Math.max(0,h.time.findIndex(t=>new Date(t)>=new Date())),soil=Number(h.soil_moisture_0_to_1cm[start]),vpd=Number(h.vapour_pressure_deficit[start]),et0=Number(p.daily.et0_fao_evapotranspiration[0]),rain3=day.precipitation_sum.slice(0,3).reduce((sum,value)=>sum+Number(value||0),0),min3=Math.min(...day.temperature_2m_min.slice(0,3)),gust3=Math.max(...day.wind_gusts_10m_max.slice(0,3));score-=Math.max(0,rain3-15)*1.7+Math.max(0,gust3-35)*1.5+(min3<=0?28:0)+(soil<.12?22:soil>.42?18:0)+(vpd>1.6?14:0);add('Umidità suolo',`${(soil*100).toFixed(0)}%`,soil>=.12&&soil<=.42?'good':'warn');add('Pioggia 3 giorni',`${rain3.toFixed(1)} mm`,rain3<=20?'good':'warn');add('ET₀ oggi',`${et0.toFixed(1)} mm`,et0<5?'good':'warn');add('VPD',`${vpd.toFixed(1)} kPa`,vpd<=1.6?'good':'warn');advice=min3<=0?'Possibile gelo: proteggi le colture sensibili e verifica le minime locali.':soil<.12&&rain3<5?'Strato superficiale asciutto e poca pioggia prevista: valuta irrigazione in base a coltura e terreno.':rain3>20?'Piogge significative previste: rimanda lavorazioni che richiedono terreno asciutto.':'Quadro utile per lavorazioni ordinarie; confronta sempre il dato con sensori e condizioni reali del campo.'}
 if(selectedSpecialProfile==='construction'){const p=professionalData,hours=Number(p.daily.precipitation_hours[0]||0),snow=Number(p.daily.snowfall_sum[0]||0),maxGust=Math.max(...day.wind_gusts_10m_max.slice(0,2)),maxRain=Math.max(...day.precipitation_probability_max.slice(0,2));score-=maxRain*.45+Math.max(0,maxGust-35)*2+hours*4+snow*8+Math.max(0,3-day.temperature_2m_min[0])*5+Math.max(0,day.temperature_2m_max[0]-35)*3;add('Raffiche',`${Math.round(maxGust)} km/h`,maxGust<40?'good':'warn');add('Ore pioggia',`${hours.toFixed(0)} h`,hours<=2?'good':'warn');add('Neve',`${snow.toFixed(1)} cm`,snow===0?'good':'warn');add('Temperatura',`${Math.round(day.temperature_2m_min[0])}–${Math.round(day.temperature_2m_max[0])}°`,day.temperature_2m_min[0]>3&&day.temperature_2m_max[0]<35?'good':'warn');advice=maxGust>=45?'Raffiche incompatibili con molte lavorazioni in quota, gru e materiali esposti: applica il piano di sicurezza del cantiere.':hours>3||maxRain>=60?'Prevedi protezioni, coperture e possibili interruzioni per superfici o lavorazioni sensibili all’acqua.':'Finestra operativa discreta; restano vincolanti piano di sicurezza e misurazioni sul cantiere.'}
 if(selectedSpecialProfile==='hiking'){const p=professionalData,h=p.hourly,start=Math.max(0,h.time.findIndex(t=>new Date(t)>=new Date())),routeVisibility=Number(h.visibility[start])/1000,snow=Number(p.daily.snowfall_sum[0]||0),maxGust=Math.max(...day.wind_gusts_10m_max.slice(0,2));score-=rain*.65+Math.max(0,maxGust-35)*2+(routeVisibility<5?28:0)+Math.max(0,uv-7)*5+snow*7+Math.max(0,5-day.temperature_2m_min[0])*3;add('Visibilità',`${routeVisibility.toFixed(1)} km`,routeVisibility>=5?'good':'warn');add('Raffiche',`${Math.round(maxGust)} km/h`,maxGust<40?'good':'warn');add('Pioggia',`${Math.round(rain)}%`,rain<35?'good':'warn');add('Neve',`${snow.toFixed(1)} cm`,snow===0?'good':'warn');advice=routeVisibility<5||maxGust>=45?'Visibilità o raffiche richiedono un itinerario più semplice, riparato o il rinvio dell’escursione.':rain>=50?'Porta equipaggiamento impermeabile e valuta un percorso con vie di rientro rapide.':'Condizioni complessivamente gestibili, ma quota, terreno e capacità personali non sono deducibili dal meteo.'}
 if(selectedSpecialProfile==='photography'){const p=professionalData,h=p.hourly,start=Math.max(0,h.time.findIndex(t=>new Date(t)>=new Date())),cloud=Number(h.cloud_cover[start]),photoVisibility=Number(h.visibility[start])/1000,sunshine=Number(p.daily.sunshine_duration[0]||0)/3600,rise=new Date(day.sunrise[0]).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}),set=new Date(day.sunset[0]).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});score-=Math.abs(cloud-45)*.45+rain*.25+(photoVisibility<8?22:0);add('Nuvole',`${Math.round(cloud)}%`,cloud>=15&&cloud<=75?'good':'warn');add('Visibilità',`${photoVisibility.toFixed(1)} km`,photoVisibility>=8?'good':'warn');add('Sole utile',`${sunshine.toFixed(1)} h`,'good');add('Ore dorate',`${rise} / ${set}`,'good');advice=rain>=60?'Proteggi l’attrezzatura: la luce può essere interessante, ma sono probabili precipitazioni.':cloud>=20&&cloud<=70?`Copertura interessante per luce modellata; pianifica alba alle ${rise} o tramonto alle ${set}.`:`Cielo ${cloud<20?'molto limpido':'molto coperto'}: adatta soggetto, contrasto e orario di scatto.`}
 score=Math.max(0,Math.min(100,Math.round(score)));if(rule.marine&&!lastMarine){score=Math.min(score,64);if(marineAutoFailed){advice='I dati del mare non sono momentaneamente disponibili. Meteo AI riproverà alla prossima selezione di un profilo marino.';factors.push('<span class="warn"><b>MARE AI</b>Dati temporaneamente non disponibili</span>')}else{advice='Mare AI sta caricando automaticamente onde, periodo e correnti per completare questa valutazione.';factors.push('<span><b>MARE AI</b>Caricamento automatico</span>');setTimeout(autoLoadMarine,0)}}const status=score>=80?'Condizioni favorevoli':score>=60?'Condizioni discrete':score>=40?'Serve prudenza':'Meglio rimandare';
 $('#profileScore').textContent=score;$('#profileName').textContent=rule.name.toUpperCase();$('#profileStatus').textContent=status;$('#profileAdvice').textContent=advice;$('#profileFactors').innerHTML=factors.join('');
}
$$('[data-special-profile]').forEach(button=>button.onclick=()=>{$$('[data-special-profile]').forEach(x=>x.classList.toggle('active',x===button));selectedSpecialProfile=button.dataset.specialProfile;if(specialProfileRules[selectedSpecialProfile]?.marine&&!lastMarine)marineAutoFailed=false;renderSpecialProfile()});

function autoLoadMarine(){const button=$('#marineLoadBtn');if(lastMarine||marineAutoPending||button?.disabled)return;marineAutoPending=true;loadMarine().finally(()=>{marineAutoPending=false;if(!lastMarine){marineAutoFailed=true;renderSpecialProfile()}})}

async function ensureProfessionalData(){if(professionalLoading||professionalData||!lastData)return;const key=professionalPlaceKey,place={latitude:lastPlace.latitude,longitude:lastPlace.longitude},cacheKey=`professional-v1-${key}`;professionalLoading=true;renderSpecialProfile();try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<1800000){professionalData=cached.data;professionalLoading=false;renderSpecialProfile();return}}catch(_){}const params=new URLSearchParams({latitude:place.latitude,longitude:place.longitude,timezone:'auto',forecast_days:7,hourly:'cloud_cover,visibility,soil_moisture_0_to_1cm,vapour_pressure_deficit,shortwave_radiation,precipitation,wind_gusts_10m,temperature_2m',daily:'et0_fao_evapotranspiration,sunshine_duration,snowfall_sum,precipitation_hours'});try{const response=await fetchResilient(`https://api.open-meteo.com/v1/forecast?${params}`);if(!response.ok)throw Error();const data=await response.json();if(key!==professionalPlaceKey)return;professionalData=data;try{sessionStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),data}))}catch(_){}}catch(_){if(key===professionalPlaceKey)professionalData={error:true}}finally{if(key===professionalPlaceKey){professionalLoading=false;renderSpecialProfile()}}}

function resetProbability(){const result=$('#probabilityResult'),empty=$('#probabilityEmpty'),button=$('#probabilityLoadBtn');if(!result||!empty||!button)return;result.classList.add('hidden');empty.classList.remove('hidden');button.disabled=false;button.textContent='Verifica accordo e probabilità';empty.innerHTML='<b>Cosa ottieni</b><p>Un indicatore di accordo tra modelli e probabilità di pioggia o vento calcolate su 51 possibili scenari ECMWF.</p>'}
function percentile(values,p){const sorted=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!sorted.length)return NaN;return sorted[Math.round((sorted.length-1)*p)]}
function dayValues(hourly,key,date,mode='max'){const indices=hourly.time.map((t,i)=>t.startsWith(date)?i:-1).filter(i=>i>=0),values=indices.map(i=>Number(hourly[key]?.[i])).filter(Number.isFinite);if(!values.length)return NaN;return mode==='sum'?values.reduce((a,b)=>a+b,0):Math.max(...values)}
function regionalModelDescriptor(place){const code=String(place.country_code||'').toUpperCase(),labels={IT:'Best Match locale · priorità ItaliaMeteo / ICON',FR:'Best Match locale · priorità Météo-France AROME',US:'Best Match locale · priorità NOAA HRRR / NBM',CA:'Best Match locale · priorità GEM HRDPS',JP:'Best Match locale · priorità JMA MSM',KR:'Best Match locale · priorità KMA LDPS',GB:'Best Match locale · priorità UK Met Office',CH:'Best Match locale · priorità MeteoSwiss ICON',AT:'Best Match locale · priorità GeoSphere AROME',NL:'Best Match locale · priorità KNMI HARMONIE',DE:'Best Match locale · priorità DWD ICON-D2',CZ:'Best Match locale · priorità CHMI ALADIN / ICON',AU:'Best Match locale · priorità BOM ACCESS',NO:'Best Match locale · priorità MET Nordic',SE:'Best Match locale · priorità MET Nordic',DK:'Best Match locale · priorità MET Nordic',FI:'Best Match locale · priorità MET Nordic'};return labels[code]||'Best Match ad alta risoluzione disponibile per la zona'}
function adaptiveWeight(model,dayIndex){if(model==='best_match')return dayIndex<=2?2.4:dayIndex<=6?1.6:1.1;if(model==='ecmwf_ifs025')return dayIndex<=2?1.2:dayIndex<=6?1.45:1.65;if(model==='icon_seamless')return dayIndex<=6?1.2:.8;return dayIndex<=6?1:1.2}
function weightedValue(stats,key,dayIndex){let total=0,weights=0;stats.forEach(item=>{if(Number.isFinite(item[key])){const weight=adaptiveWeight(item.model,dayIndex);total+=item[key]*weight;weights+=weight}});return weights?total/weights:NaN}
async function loadProbabilityAnalysis(){
 const button=$('#probabilityLoadBtn'),place={...lastPlace},cacheKey=`adaptive-probability-v2-${Number(place.latitude).toFixed(3)}-${Number(place.longitude).toFixed(3)}`;button.disabled=true;button.textContent='Confronto 55 scenari…';$('#probabilityEmpty').innerHTML='<b>Valuto la stabilità della previsione</b><p>Confronto quattro modelli e 51 scenari ECMWF per misurare differenze e probabilità.</p>';
 try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<3600000){renderProbability(cached.data);return}}catch(_){}
 const base={latitude:place.latitude,longitude:place.longitude,timezone:'auto',forecast_days:7,hourly:'temperature_2m,precipitation,wind_speed_10m'},detParams=new URLSearchParams({...base,models:'ecmwf_ifs025,gfs_seamless,icon_seamless,best_match'}),ensParams=new URLSearchParams({...base,models:'ecmwf_ifs025'});
 try{const [detResponse,ensResponse]=await Promise.all([fetchResilient(`https://api.open-meteo.com/v1/forecast?${detParams}`),fetchResilient(`https://ensemble-api.open-meteo.com/v1/ensemble?${ensParams}`)]);if(!detResponse.ok||!ensResponse.ok)throw Error();const deterministic=await detResponse.json(),ensemble=await ensResponse.json(),data=calculateProbability(deterministic,ensemble,regionalModelDescriptor(place));if(lastPlace.latitude!==place.latitude||lastPlace.longitude!==place.longitude)return;try{sessionStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),data}))}catch(_){}renderProbability(data)}catch(_){button.disabled=false;button.textContent='Riprova l’analisi';$('#probabilityEmpty').innerHTML='<b>Analisi momentaneamente non disponibile</b><p>La richiesta ensemble è più pesante del meteo normale. Riprova tra qualche minuto.</p>'}
}
function calculateProbability(deterministic,ensemble,regionalLabel){
 const dates=[...new Set(ensemble.hourly.time.map(t=>t.slice(0,10)))].slice(0,7),models=['ecmwf_ifs025','gfs_seamless','icon_seamless','best_match'],suffixes=Object.keys(ensemble.hourly).filter(k=>k==='temperature_2m'||/^temperature_2m_member\d+$/.test(k)).map(k=>k.slice('temperature_2m'.length));let agreementTotal=0,influenceTotal=0;
 const days=dates.map((date,dayIndex)=>{const modelStats=models.map(model=>({model,temp:dayValues(deterministic.hourly,`temperature_2m_${model}`,date),rain:dayValues(deterministic.hourly,`precipitation_${model}`,date,'sum'),wind:dayValues(deterministic.hourly,`wind_speed_10m_${model}`,date)})).filter(item=>Number.isFinite(item.temp)),temps=modelStats.map(x=>x.temp),winds=modelStats.map(x=>x.wind).filter(Number.isFinite),rainVotes=modelStats.filter(x=>Number.isFinite(x.rain)).map(x=>x.rain>=1),tempSpread=Math.max(...temps)-Math.min(...temps),windSpread=winds.length?Math.max(...winds)-Math.min(...winds):0,majority=rainVotes.filter(Boolean).length>=rainVotes.length/2,rainAgreement=rainVotes.filter(x=>x===majority).length/Math.max(1,rainVotes.length)*100,agreement=Math.round((Math.max(0,100-tempSpread*18)+Math.max(0,100-windSpread*4)+rainAgreement)/3),availableWeight=modelStats.reduce((sum,item)=>sum+adaptiveWeight(item.model,dayIndex),0),localWeight=modelStats.some(item=>item.model==='best_match')?adaptiveWeight('best_match',dayIndex):0;agreementTotal+=agreement;if(dayIndex<3)influenceTotal+=localWeight/Math.max(1,availableWeight)*100;const members=suffixes.map(suffix=>({temp:dayValues(ensemble.hourly,`temperature_2m${suffix}`,date),rain:dayValues(ensemble.hourly,`precipitation${suffix}`,date,'sum'),wind:dayValues(ensemble.hourly,`wind_speed_10m${suffix}`,date)})).filter(x=>Number.isFinite(x.temp));return{date,agreement,consensusTemp:weightedValue(modelStats,'temp',dayIndex),consensusRain:weightedValue(modelStats,'rain',dayIndex),consensusWind:weightedValue(modelStats,'wind',dayIndex),tempLow:percentile(members.map(x=>x.temp),.1),tempHigh:percentile(members.map(x=>x.temp),.9),rainProbability:Math.round(members.filter(x=>x.rain>=1).length/Math.max(1,members.length)*100),strongWindProbability:Math.round(members.filter(x=>x.wind>=35).length/Math.max(1,members.length)*100),members:members.length,models:modelStats.length}});
 return{agreement:Math.round(agreementTotal/Math.max(1,days.length)),regionalInfluence:Math.round(influenceTotal/Math.min(3,days.length)),regionalLabel,days};
}
function renderProbability(data){const button=$('#probabilityLoadBtn');button.disabled=false;button.textContent='Aggiorna l’analisi';$('#probabilityEmpty').classList.add('hidden');$('#probabilityResult').classList.remove('hidden');$('#modelAgreement').textContent=`${data.agreement}%`;$('#modelAgreementText').textContent=data.agreement>=80?'Previsione stabile: i quattro modelli descrivono uno scenario molto simile.':data.agreement>=60?'Previsione abbastanza stabile, ma restano alcune differenze.':'Previsione incerta: i modelli divergono, quindi ricontrolla più avanti.';$('#regionalModelName').textContent=data.regionalLabel;$('#adaptiveSummary').textContent=`Nei primi tre giorni il modello locale contribuisce in media per il ${data.regionalInfluence}%; più avanti diventano più utili i modelli globali.`;$('#adaptiveMetrics').innerHTML='<span><b>Accordo alto</b> Previsione più stabile</span><span><b>Accordo basso</b> Maggiore incertezza</span><span><b>Probabilità</b> 51 scenari possibili</span>';$('#probabilityDays').innerHTML=data.days.map((day,i)=>`<article><span>${i===0?'Oggi':new Date(day.date+'T12:00').toLocaleDateString('it-IT',{weekday:'short',day:'numeric'})}</span><b>${Math.round(day.consensusTemp)}°</b><small>Temperatura probabile: ${Math.round(day.tempLow)}–${Math.round(day.tempHigh)}° nell’80% degli scenari</small><p class="adaptive-day-stats"><span>Pioggia media <b>${day.consensusRain.toFixed(1)} mm</b></span><span>Vento max <b>${Math.round(day.consensusWind)} km/h</b></span></p><div><em style="--chance:${day.rainProbability}%"></em><strong>Possibilità di pioggia: ${day.rainProbability}%</strong></div><div><em style="--chance:${day.strongWindProbability}%"></em><strong>Possibilità di vento forte: ${day.strongWindProbability}%</strong></div><small>${day.models} modelli • ${day.members} scenari • stabilità ${day.agreement}%</small></article>`).join('')}
$('#probabilityLoadBtn')?.addEventListener('click',loadProbabilityAnalysis);
function cardinal(deg){if(!Number.isFinite(Number(deg)))return '--';return ['Nord','Nord-Est','Est','Sud-Est','Sud','Sud-Ovest','Ovest','Nord-Ovest'][Math.round(Number(deg)/45)%8]}
function beaufort(kmh){const limits=[1,6,12,20,29,39,50,62,75,89,103,118],labels=['Calma','Bava di vento','Brezza leggera','Brezza tesa','Vento moderato','Vento teso','Vento fresco','Vento forte','Burrasca','Burrasca forte','Tempesta','Fortunale','Uragano'];const level=limits.findIndex(x=>kmh<x);const n=level<0?12:level;return [n,labels[n]]}
function renderWind(d){const c=d.current,speed=Math.round(c.wind_speed_10m||0),gust=Math.round(c.wind_gusts_10m||speed),direction=Math.round(c.wind_direction_10m||0),force=beaufort(speed);$('#windSpeedDetail').textContent=speed;$('#windGust').textContent=gust;$('#windDirectionLabel').textContent=cardinal(direction);$('#windDirectionDegrees').textContent=`${direction}°`;$('#windArrow').style.transform=`rotate(${direction}deg)`;$('#windBeaufort').textContent=force[0];$('#windBeaufortLabel').textContent=force[1];const status=gust>=75?'Raffiche molto forti':gust>=50?'Vento forte':gust>=30?'Vento sostenuto':speed<6?'Quasi calmo':'Vento gestibile';$('#windStatus').textContent=status;$('#windAdvice').textContent=gust>=50?'Evita attività esposte e controlla gli avvisi ufficiali locali.':gust>=30?'Bicicletta, mare e attività esposte richiedono prudenza.':'Non emergono criticità importanti per le normali attività.';const h=d.hourly,now=new Date(),start=Math.max(0,h.time.findIndex(t=>new Date(t)>=now)),end=Math.min(h.time.length,start+24);let best=start,bestValue=Infinity;for(let i=start;i<end-2;i++){const avg=(h.wind_speed_10m[i]+h.wind_speed_10m[i+1]+h.wind_speed_10m[i+2])/3+(h.wind_gusts_10m[i]+h.wind_gusts_10m[i+1]+h.wind_gusts_10m[i+2])/9;if(avg<bestValue){bestValue=avg;best=i}}const from=new Date(h.time[best]),to=new Date(h.time[Math.min(best+2,h.time.length-1)]);$('#windBestWindow').textContent=`${from.toLocaleDateString('it-IT',{weekday:'short'})} ${from.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}–${to.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`;$('#windHours').innerHTML=h.time.slice(start,start+12).map((t,j)=>{const i=start+j,dir=Math.round(h.wind_direction_10m[i]||0);return `<div class="wind-hour"><span>${new Date(t).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><i style="transform:rotate(${dir}deg)">↑</i><b>${Math.round(h.wind_speed_10m[i])} km/h</b><small>Raffiche ${Math.round(h.wind_gusts_10m[i])}</small></div>`}).join('');$('#windDays').innerHTML=d.daily.time.map((t,i)=>`<div class="wind-day"><span>${i===0?'Oggi':new Date(t+'T12:00').toLocaleDateString('it-IT',{weekday:'short',day:'numeric'})}</span><i style="transform:rotate(${Math.round(d.daily.wind_direction_10m_dominant[i]||0)}deg)">↑</i><b>${Math.round(d.daily.wind_speed_10m_max[i])} km/h</b><small>Raffiche ${Math.round(d.daily.wind_gusts_10m_max[i])}</small></div>`).join('')}
function drawChart(d){const canvas=$('#weatherChart');if(!canvas)return;const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=rect.width*ratio;canvas.height=260*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const w=rect.width,h=260,p={l:38,r:18,t:20,b:34};const now=new Date(),start=Math.max(0,d.hourly.time.findIndex(t=>new Date(t)>=now)),temps=d.hourly.temperature_2m.slice(start,start+24),rain=d.hourly.precipitation_probability.slice(start,start+24),times=d.hourly.time.slice(start,start+24),min=Math.floor(Math.min(...temps)-2),max=Math.ceil(Math.max(...temps)+2),x=i=>p.l+i*(w-p.l-p.r)/(temps.length-1),y=v=>p.t+(max-v)*(h-p.t-p.b)/(max-min);ctx.clearRect(0,0,w,h);ctx.font='11px DM Sans';ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');for(let i=0;i<4;i++){const yy=p.t+i*(h-p.t-p.b)/3;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillText(Math.round(max-i*(max-min)/3)+'°',2,yy+4)}ctx.fillStyle='rgba(97,174,221,.18)';ctx.beginPath();rain.forEach((v,i)=>{const yy=h-p.b-v*(h-p.t-p.b)/100;i?ctx.lineTo(x(i),yy):ctx.moveTo(x(i),yy)});ctx.lineTo(x(rain.length-1),h-p.b);ctx.lineTo(x(0),h-p.b);ctx.fill();ctx.strokeStyle='#0d7b57';ctx.lineWidth=3;ctx.beginPath();temps.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke();ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');times.forEach((t,i)=>{if(i%4===0)ctx.fillText(new Date(t).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}),x(i)-13,h-10)})}
function renderAI(d){const x=d.daily,max=Math.round(x.temperature_2m_max[0]),rain=x.precipitation_probability_max[0],wind=Math.round(d.current.wind_speed_10m),uv=x.uv_index_max[0];let parts=[`Oggi a ${lastPlace.name} sono previsti ${weather(x.weather_code[0])[0].toLowerCase()} e una massima di ${max}°.`];if(rain>=60)parts.push(`La probabilità di pioggia è alta (${rain}%): pianifica con prudenza le attività all'aperto.`);else if(rain>=30)parts.push(`Possibili precipitazioni locali (${rain}%), soprattutto nelle ore più instabili.`);else parts.push('Il rischio di pioggia resta contenuto.');if(wind>35)parts.push(`Vento sostenuto fino a circa ${wind} km/h.`);$('#aiSummary').textContent=parts.join(' ');let advice=uv>=6?'Protezione solare consigliata nelle ore centrali.':rain>=50?'Porta con te un ombrello e controlla gli aggiornamenti.':'Condizioni favorevoli per le normali attività quotidiane.';$('#advice p').textContent=advice}
async function choose(q){const places=await searchPlaces(q);if(!places.length)return toast('Località non trovata');$('#suggestions').classList.remove('open');selectWeatherPlace(places[0])}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#placeInput').value.trim();if(q)choose(q)});let timer;$('#placeInput').addEventListener('input',e=>{clearTimeout(timer);const q=e.target.value.trim();if(q.length<2)return $('#suggestions').classList.remove('open');timer=setTimeout(async()=>{const list=await searchPlaces(q);$('#suggestions').innerHTML=list.map((p,i)=>`<button type="button" data-i="${i}"><b>${p.name}</b> — ${p.admin1||''}, ${p.country||''}</button>`).join('');$('#suggestions').classList.toggle('open',!!list.length);$$('#suggestions button').forEach(b=>b.onclick=()=>{const p=list[+b.dataset.i];$('#placeInput').value=p.name;$('#suggestions').classList.remove('open');selectWeatherPlace(p)})},300)});$$('[data-place]').forEach(b=>b.onclick=()=>choose(b.dataset.place));
function openLocationModal(){$('#locationInput').value=lastPlace.name||'';$('#locationSuggestions').innerHTML='';$('#locationModal').showModal();setTimeout(()=>$('#locationInput').select(),50)}
$('#locationMenuBtn').onclick=openLocationModal;$('#currentLocationBtn').onclick=openLocationModal;
function setSectionsOpen(open){const menu=$('#sectionsMenu');menu.classList.toggle('open',open);['#sectionsMenuBtn','#mobileMenuBtn','#mobileSectionsBtn'].forEach(selector=>$(selector)?.setAttribute('aria-expanded',String(open)))}
function toggleSections(){setSectionsOpen(!$('#sectionsMenu').classList.contains('open'))}
$('#sectionsMenuBtn').onclick=toggleSections;$('#mobileMenuBtn').onclick=toggleSections;$('#mobileSectionsBtn').onclick=toggleSections;$$('#sectionsMenu a,.quick-sections a,.mobile-bottom-nav a').forEach(a=>a.onclick=()=>setSectionsOpen(false));document.addEventListener('click',e=>{if(!e.target.closest('#sectionsMenu')&&!e.target.closest('#sectionsMenuBtn')&&!e.target.closest('#mobileMenuBtn')&&!e.target.closest('#mobileSectionsBtn'))setSectionsOpen(false)});
$('#locationForm').onsubmit=async e=>{e.preventDefault();const q=$('#locationInput').value.trim();if(!q)return;const places=await searchPlaces(q);if(!places.length)return toast('Località non trovata');$('#locationModal').close();selectWeatherPlace(places[0])};let locationTimer;$('#locationInput').oninput=e=>{clearTimeout(locationTimer);const q=e.target.value.trim();if(q.length<2)return $('#locationSuggestions').innerHTML='';locationTimer=setTimeout(async()=>{const list=await searchPlaces(q);$('#locationSuggestions').innerHTML=list.map((p,i)=>`<button type="button" data-location-i="${i}"><b>${p.name}</b><span>${p.admin1||''}${p.country?', '+p.country:''}</span></button>`).join('');$$('[data-location-i]').forEach(b=>b.onclick=()=>{const p=list[+b.dataset.locationI];$('#locationModal').close();selectWeatherPlace(p)})},250)};
async function reverseDeviceLocation(latitude,longitude){try{const response=await fetchResilient(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=it`);if(!response.ok)throw Error();const data=await response.json(),name=data.city||data.locality||data.principalSubdivision||'Posizione attuale';return{name,country:data.countryName||'',country_code:data.countryCode||'',admin1:data.principalSubdivision||'',latitude,longitude}}catch(_){return{name:'Posizione attuale',country:'',latitude,longitude}}}
function useDeviceLocation({silent=false}={}){if(!navigator.geolocation){if(!silent)toast('Geolocalizzazione non supportata');return Promise.resolve(false)}if(!window.isSecureContext){if(!silent)toast('Il GPS richiede una connessione sicura HTTPS');return Promise.resolve(false)}return new Promise(resolve=>navigator.geolocation.getCurrentPosition(async position=>{const latitude=position.coords.latitude,longitude=position.coords.longitude,place=await reverseDeviceLocation(latitude,longitude);try{localStorage.setItem('meteo-location-mode','gps')}catch(_){}loadWeather(place);resolve(true)},error=>{if(!silent)toast(error.code===1?'Permesso GPS non concesso':'Posizione non disponibile');resolve(false)},{enableHighAccuracy:false,timeout:10000,maximumAge:600000}))}
$('#geoBtn').onclick=()=>useDeviceLocation();
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('meteo-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('meteo-theme')==='dark')document.body.classList.add('dark');
function savePlace(){const arr=JSON.parse(localStorage.getItem('meteo-places')||'[]');if(arr.some(x=>x.latitude===lastPlace.latitude&&x.longitude===lastPlace.longitude))return toast('Località già salvata');arr.push(lastPlace);localStorage.setItem('meteo-places',JSON.stringify(arr));renderSaved();toast('Località salvata soltanto su questo dispositivo')}
function renderSaved(){const arr=JSON.parse(localStorage.getItem('meteo-places')||'[]');$('#savedList').innerHTML=arr.length?arr.map((p,i)=>`<div class="saved-item"><button data-open="${i}"><b>${p.name}</b><br><small>${p.country||''}</small></button><button class="remove" data-remove="${i}" aria-label="Rimuovi">×</button></div>`).join(''):'<p>Nessuna località salvata.</p>';$$('[data-open]').forEach(b=>b.onclick=()=>{loadWeather(arr[+b.dataset.open]);closeDrawer()});$$('[data-remove]').forEach(b=>b.onclick=()=>{arr.splice(+b.dataset.remove,1);localStorage.setItem('meteo-places',JSON.stringify(arr));renderSaved()})}
function closeDrawer(){$('#savedDrawer').classList.remove('open');$('#overlay').classList.remove('open')}
$('#saveBtn').onclick=savePlace;$('#savedBtn').onclick=()=>{$('#savedDrawer').classList.add('open');$('#overlay').classList.add('open');renderSaved()};$('#overlay').onclick=closeDrawer;$$('[data-close]').forEach(b=>b.onclick=closeDrawer);
$$('[data-unit]').forEach(b=>b.onclick=()=>{unit=b.dataset.unit;$$('[data-unit]').forEach(x=>x.classList.toggle('active',x===b));if(lastData){renderDaily(lastData);renderNextTwoDays(lastData)}});
$('#compareBtn').onclick=async()=>{const q=$('#compareInput').value.trim();if(!q)return toast('Inserisci una località');$('#compareResult').innerHTML='Confronto in corso...';try{const p=(await searchPlaces(q))[0];if(!p)throw Error();const u=new URLSearchParams({latitude:p.latitude,longitude:p.longitude,timezone:'auto',forecast_days:1,current:'temperature_2m,weather_code,wind_speed_10m',daily:'temperature_2m_max,precipitation_probability_max'});const d=await (await fetchResilient(`https://api.open-meteo.com/v1/forecast?${u}`)).json();const a=lastData.current,b=d.current;$('#compareResult').innerHTML=`<div class="compare-cities"><div><b>${lastPlace.name}</b><strong>${Math.round(a.temperature_2m)}° ${weather(a.weather_code)[1]}</strong><small>Pioggia ${lastData.daily.precipitation_probability_max[0]}%</small></div><span>VS</span><div><b>${p.name}</b><strong>${Math.round(b.temperature_2m)}° ${weather(b.weather_code)[1]}</strong><small>Pioggia ${d.daily.precipitation_probability_max[0]}%</small></div></div>`}catch(e){$('#compareResult').textContent='Impossibile confrontare questa località.'}};
$$('[data-ai-activity]').forEach(b=>b.onclick=()=>{selectedActivity=b.dataset.aiActivity;$$('[data-ai-activity]').forEach(x=>x.classList.toggle('active',x===b));if(lastData)renderWeatherWindow(lastData)});
function resetMarine(){const empty=$('#marineEmpty'),dashboard=$('#marineDashboard'),button=$('#marineLoadBtn');if(!empty||!dashboard||!button)return;empty.classList.remove('hidden');dashboard.classList.add('hidden');button.disabled=false;button.textContent='Aggiorna analisi';empty.innerHTML='<div class="marine-symbol loading-wave">≈</div><h4>Analisi automatica del mare</h4><p>Sto selezionando il punto marino modellistico più vicino alla località.</p>'}
function distanceKm(a,b,c,d){const r=6371,p=x=>x*Math.PI/180,dp=p(c-a),dl=p(d-b),q=Math.sin(dp/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
function marineValue(value,digits=1,suffix=''){return Number.isFinite(Number(value))?`${Number(value).toFixed(digits)}${suffix}`:`--${suffix}`}

