const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
async function fetchResilient(input,init={},options={}){
 const timeout=options.timeout||12000,retries=options.retries??1;
 let lastError;
 for(let attempt=0;attempt<=retries;attempt++){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
  try{return await window.fetch(input,{...init,signal:init.signal||controller.signal})}
  catch(error){lastError=error;if(init.signal?.aborted||attempt===retries)throw error}
  finally{clearTimeout(timer)}
 }
 throw lastError;
}
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeUrl=value=>{try{const url=new URL(String(value));return['http:','https:'].includes(url.protocol)?url.href:'#'}catch(_){return'#'}};
const defaultPlace={name:'Messina',country:'Italia',country_code:'IT',latitude:38.1939,longitude:15.554};
let referencePlace=defaultPlace,worldMap,eventLayer,locationLayer,events=[],activeType='all',activePeriod='week',activeEventId='',sourceState={},watchLocations=[],pendingWatchPlace=null,lastWorldRefresh=0,requestedEventHandled=false;

try{const stored=JSON.parse(localStorage.getItem('meteo-current-place')||'null');if(stored&&Number.isFinite(Number(stored.latitude))&&Number.isFinite(Number(stored.longitude)))referencePlace=stored}catch(_){}

const typeInfo={
 earthquake:{label:'Terremoto',icon:'≋'},tsunami:{label:'Tsunami',icon:'≈'},storm:{label:'Ciclone o tempesta',icon:'◉'},volcano:{label:'Vulcano',icon:'▲'},wildfire:{label:'Incendio',icon:'♨'},flood:{label:'Alluvione',icon:'≋'},other:{label:'Altro evento',icon:'＋'}
};
const categoryMap={severeStorms:'storm',tropicalCyclones:'storm',volcanoes:'volcano',wildfires:'wildfire',floods:'flood',landslides:'other',drought:'other',dustHaze:'other',tempExtremes:'other',seaLakeIce:'other',snow:'other'};
const severityLabels={low:'Bassa',moderate:'Moderata',high:'Alta',extreme:'Estrema'};

function placeLabel(place){return [place.name,place.admin1&&place.admin1!==place.name?place.admin1:'',place.country].filter(Boolean).join(', ')}
function distanceKm(a,b,c,d){const radius=6371,toRad=x=>x*Math.PI/180,lat=toRad(c-a),lon=toRad(d-b),value=Math.sin(lat/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(lon/2)**2;return 2*radius*Math.asin(Math.sqrt(value))}
function relativeTime(date){const seconds=Math.max(0,(Date.now()-new Date(date).getTime())/1000);if(seconds<3600)return `${Math.max(1,Math.round(seconds/60))} min fa`;if(seconds<86400)return `${Math.round(seconds/3600)} ore fa`;return `${Math.round(seconds/86400)} giorni fa`}
function formatDistance(km){if(!Number.isFinite(km))return 'Distanza non disponibile';return km<10?`${km.toFixed(1)} km`:km<1000?`${Math.round(km)} km`:`${(km/1000).toFixed(1)} mila km`}
function levelFromScore(score){return score>=82?'extreme':score>=62?'high':score>=38?'moderate':'low'}
function centroid(geometry){if(!geometry)return null;if(geometry.type==='Point')return{lon:Number(geometry.coordinates[0]),lat:Number(geometry.coordinates[1])};const points=[];const visit=value=>{if(Array.isArray(value)&&typeof value[0]==='number')points.push(value);else if(Array.isArray(value))value.forEach(visit)};visit(geometry.coordinates);if(!points.length)return null;return{lon:points.reduce((sum,p)=>sum+Number(p[0]),0)/points.length,lat:points.reduce((sum,p)=>sum+Number(p[1]),0)/points.length}}
function impactFor(event){const distance=distanceKm(referencePlace.latitude,referencePlace.longitude,event.lat,event.lon),base=event.severityScore,range=event.type==='earthquake'?900:event.type==='tsunami'?1400:event.type==='storm'?1800:event.type==='volcano'?700:event.type==='wildfire'?350:500;const proximity=Math.max(.04,1/(1+distance/range)),freshness=Math.max(.35,1-Math.max(0,Date.now()-new Date(event.date).getTime())/(35*864e5));let impact=Math.round(base*proximity*freshness);if(event.type==='tsunami'&&distance<1800)impact=Math.max(impact,Math.round(base*.55));return{distance,impact:Math.max(0,Math.min(100,impact))}}
function enrich(event){const result=impactFor(event);event.distance=result.distance;event.impact=result.impact;event.level=levelFromScore(event.severityScore);return event}

function initMap(){
 worldMap=L.map('worldMap',{worldCopyJump:true,minZoom:2,zoomControl:true}).setView([18,8],2);
 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:12,attribution:'© OpenStreetMap'}).addTo(worldMap);
 eventLayer=L.layerGroup().addTo(worldMap);locationLayer=L.layerGroup().addTo(worldMap);renderReferenceMarker()
}
function renderReferenceMarker(){locationLayer.clearLayers();const marker=L.marker([referencePlace.latitude,referencePlace.longitude],{icon:L.divIcon({className:'',html:'<div class="location-marker"></div>',iconSize:[18,18],iconAnchor:[9,9]})});marker.bindTooltip(`<b>${esc(placeLabel(referencePlace))}</b><br>Località di riferimento`);marker.addTo(locationLayer);$('#worldLocationName').textContent=placeLabel(referencePlace)}

async function fetchJSONCached(key,url,force=false){const cacheKey=`world-live-${key}`;if(!force)try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<600000)return cached.data}catch(_){}const response=await fetchResilient(url);if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();try{sessionStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),data}))}catch(_){}return data}
async function fetchTextCached(key,url,force=false,maxAge=600000){const cacheKey=`world-live-${key}`;if(!force)try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached&&Date.now()-cached.savedAt<maxAge)return cached.text}catch(_){}const response=await fetchResilient(url);if(!response.ok)throw Error(`HTTP ${response.status}`);const text=await response.text();try{sessionStorage.setItem(cacheKey,JSON.stringify({savedAt:Date.now(),text}))}catch(_){}return text}
function quakeScore(magnitude,significance=0){return Math.min(100,Math.round(10+Math.max(0,magnitude-2.5)*18+Math.min(18,Number(significance||0)/60)))}
async function loadEarthquakes(force=false){
 const feed={day:'2.5_day',week:'2.5_week',month:'2.5_month'}[activePeriod];
 const data=await fetchJSONCached(`usgs-${feed}`,`https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/${feed}.geojson`,force);
 return (data.features||[]).map(feature=>{const p=feature.properties||{},coordinates=feature.geometry?.coordinates||[];return enrich({id:`usgs-${feature.id}`,type:'earthquake',title:p.title||`Terremoto M ${p.mag}`,place:p.place||'Località non indicata',date:new Date(p.time).toISOString(),lat:Number(coordinates[1]),lon:Number(coordinates[0]),severityScore:quakeScore(Number(p.mag||0),p.sig),metricLabel:'Magnitudo',metricValue:`M ${Number(p.mag||0).toFixed(1)}`,secondaryLabel:'Profondità',secondaryValue:`${Math.round(Number(coordinates[2]||0))} km`,probability:null,probabilityNote:'I terremoti non possono essere previsti nel breve periodo. La fonte descrive un evento già osservato.',description:`Evento sismico registrato dall’USGS${p.felt?` con ${p.felt} segnalazioni percepite`:''}.${p.tsunami?' L’evento è contrassegnato come potenzialmente collegato a prodotti tsunami: verifica gli avvisi ufficiali.':''}`,source:'USGS',sourceUrl:p.url||'https://earthquake.usgs.gov/',officialLevel:p.alert?String(p.alert).toUpperCase():'Non assegnato',tsunamiFlag:Boolean(p.tsunami)})}).filter(event=>Number.isFinite(event.lat)&&Number.isFinite(event.lon))
}
function eonetType(event){const ids=(event.categories||[]).map(category=>category.id);return ids.map(id=>categoryMap[id]).find(Boolean)||'other'}
function eonetScore(type,magnitude){const base={storm:64,volcano:65,wildfire:55,flood:58,other:42}[type]||42;if(!Number.isFinite(Number(magnitude)))return base;return Math.min(95,Math.round(base+Math.log10(Math.max(1,Number(magnitude)))*7))}
async function loadEonet(force=false){
 const data=await fetchJSONCached('eonet-open','https://eonet.gsfc.nasa.gov/api/v3/events?status=open&limit=500',force);
 return (data.events||[]).map(item=>{const geometry=item.geometry?.[item.geometry.length-1],point=centroid(geometry),type=eonetType(item),magnitude=Number(item.magnitudeValue),source=item.sources?.[0];if(!point)return null;return enrich({id:`eonet-${item.id}`,type,title:item.title||typeInfo[type].label,place:item.description||'Area indicata sulla mappa',date:geometry?.date||new Date().toISOString(),lat:point.lat,lon:point.lon,severityScore:eonetScore(type,magnitude),metricLabel:item.magnitudeDescription||'Intensità fonte',metricValue:Number.isFinite(magnitude)?`${magnitude}${item.magnitudeUnit?` ${item.magnitudeUnit}`:''}`:'Non specificata',secondaryLabel:'Stato',secondaryValue:item.closed?'Concluso':'In corso',probability:null,probabilityNote:'NASA EONET cataloga l’evento osservato, ma questo elemento non contiene una probabilità numerica di evoluzione.',description:item.description||`Evento ${typeInfo[type].label.toLowerCase()} attualmente presente nel catalogo NASA EONET.`,source:'NASA EONET',sourceUrl:source?.url||item.link||'https://eonet.gsfc.nasa.gov/',officialLevel:'Evento aperto'})}).filter(Boolean)
}
function xmlElements(root,name){return[...root.getElementsByTagName('*')].filter(element=>element.localName===name)}
function xmlText(root,name){return xmlElements(root,name)[0]?.textContent?.trim()||''}
function textId(value){let hash=0;for(const char of String(value)){hash=(hash*31+char.codePointAt(0))>>>0}return hash.toString(36)}
function capPoint(root){const polygon=xmlText(root,'polygon');if(polygon){const points=polygon.split(/\s+/).map(pair=>pair.split(',').map(Number)).filter(pair=>pair.length===2&&pair.every(Number.isFinite));if(points.length)return{lat:points.reduce((sum,p)=>sum+p[0],0)/points.length,lon:points.reduce((sum,p)=>sum+p[1],0)/points.length}}const circle=xmlText(root,'circle').split(/\s+/)[0];if(circle){const [lat,lon]=circle.split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lon))return{lat,lon}}return null}
function capScore(severity,urgency,certainty){let score={Extreme:94,Severe:82,Moderate:62,Minor:36,Unknown:25}[severity]||45;if(urgency==='Immediate')score+=5;if(certainty==='Observed')score+=4;return Math.min(100,score)}
async function loadTsunami(force=false){
 const endpoints=['https://www.tsunami.gov/events/xml/PAAQCAP.xml','https://www.tsunami.gov/events/xml/PHEBCAP.xml'];
 const attempts=await Promise.allSettled(endpoints.map(async(url,index)=>{const key=`world-live-tsunami-${index}`;if(!force)try{const cached=JSON.parse(sessionStorage.getItem(key)||'null');if(cached&&Date.now()-cached.savedAt<300000)return{url,text:cached.text}}catch(_){}const response=await fetchResilient(url);if(!response.ok)throw Error();const text=await response.text();try{sessionStorage.setItem(key,JSON.stringify({savedAt:Date.now(),text}))}catch(_){}return{url,text}})),documents=attempts.filter(result=>result.status==='fulfilled').map(result=>result.value);if(!documents.length)throw Error('Feed CAP non disponibili');
 const unique=new Map();documents.forEach(({url,text})=>{const root=new DOMParser().parseFromString(text,'application/xml'),identifier=xmlText(root,'identifier'),headline=xmlText(root,'headline'),description=xmlText(root,'description'),combined=`${headline} ${description}`.toLowerCase(),point=capPoint(root);if(!point||/no tsunami (warning|advisory|watch|threat)/.test(combined))return;const severity=xmlText(root,'severity')||'Unknown',urgency=xmlText(root,'urgency')||'Unknown',certainty=xmlText(root,'certainty')||'Unknown',area=xmlText(root,'areaDesc')||'Area costiera indicata nel bollettino',sent=xmlText(root,'sent')||new Date().toISOString(),web=xmlText(root,'web')||url;unique.set(identifier||headline,enrich({id:`cap-${identifier||textId(headline)}`,type:'tsunami',title:headline||'Avviso tsunami',place:area,date:sent,lat:point.lat,lon:point.lon,severityScore:capScore(severity,urgency,certainty),metricLabel:'Gravità CAP',metricValue:severity,secondaryLabel:'Urgenza',secondaryValue:urgency,probability:certainty==='Likely'?'Probabile':certainty==='Possible'?'Possibile':certainty==='Observed'?'Osservato':certainty,probabilityNote:'Il formato CAP pubblica una valutazione qualitativa di certezza, non una percentuale.',description:description||'Messaggio emesso da un centro ufficiale di allerta tsunami.',source:'Tsunami.gov CAP',sourceUrl:web,officialLevel:severity}))});return[...unique.values()]
}
function jmaCoordinate(root){for(const element of xmlElements(root,'Coordinate')){const match=element.textContent.match(/([+-]\d+(?:\.\d+)?)([+-]\d+(?:\.\d+)?)/);if(match){const lat=Number(match[1]),lon=Number(match[2]);if(Math.abs(lat)<=90&&Math.abs(lon)<=180)return{lat,lon}}}return{lat:36.2,lon:138.25}}
function jmaScore(text){if(/大津波/.test(text))return96;if(/津波警報/.test(text))return84;if(/津波注意報/.test(text))return66;return45}
async function loadJmaTsunami(force=false){
 const feedUrl='https://www.data.jma.go.jp/developer/xml/feed/eqvol.xml',feedText=await fetchTextCached('jma-eqvol',feedUrl,force,180000),feed=new DOMParser().parseFromString(feedText,'application/xml'),entries=xmlElements(feed,'entry').map(entry=>{const title=xmlText(entry,'title');let link=xmlElements(entry,'link').map(element=>element.getAttribute('href')).find(Boolean);if(link?.startsWith('http://'))link=`https://${link.slice(7)}`;return{title,link,updated:xmlText(entry,'updated')}}).filter(entry=>entry.link&&/津波|tsunami/i.test(entry.title)).slice(0,8),attempts=await Promise.allSettled(entries.map(entry=>fetchTextCached(`jma-bulletin-${textId(entry.link)}`,entry.link,force,180000).then(text=>({entry,text})))),results=[];
 attempts.filter(result=>result.status==='fulfilled').forEach(result=>{const {entry,text}=result.value,root=new DOMParser().parseFromString(text,'application/xml'),headline=xmlText(root,'Text')||entry.title,kind=xmlText(root,'InfoKind')||entry.title,combined=`${entry.title} ${kind} ${headline}`;if(/解除|取消|cancel/i.test(combined))return;const point=jmaCoordinate(root),areas=[...new Set(xmlElements(root,'Name').map(element=>element.textContent.trim()).filter(Boolean))].slice(0,8),score=jmaScore(combined),date=xmlText(root,'ReportDateTime')||xmlText(root,'TargetDateTime')||entry.updated||new Date().toISOString();results.push(enrich({id:`jma-${textId(entry.link)}-${textId(date)}`,type:'tsunami',title:score>=90?'Allerta per grande tsunami — JMA':score>=80?'Allerta tsunami — JMA':score>=60?'Avviso tsunami — JMA':'Informazione tsunami — JMA',place:areas.join(', ')||'Giappone e Pacifico nord-occidentale',date,lat:point.lat,lon:point.lon,severityScore:score,metricLabel:'Livello JMA',metricValue:kind,secondaryLabel:'Centro',secondaryValue:'Japan Meteorological Agency',probability:null,probabilityNote:'Il bollettino JMA fornisce un livello ufficiale e aree previste, non una percentuale di probabilità.',description:headline||'Bollettino tsunami pubblicato dalla Japan Meteorological Agency.',source:'JMA',sourceUrl:entry.link,officialLevel:kind}))});return results
}
async function loadBmkgTsunami(force=false){
 const data=await fetchJSONCached('bmkg-autogempa','https://data.bmkg.go.id/DataMKG/TEWS/autogempa.json',force),quake=data.Infogempa?.gempa;if(!quake)throw Error('Dati BMKG non validi');const potential=String(quake.Potensi||''),hasTsunami=/tsunami/i.test(potential)&&!/tidak|non|no tsunami/i.test(potential);if(!hasTsunami)return[];const coordinates=String(quake.Coordinates||'').split(',').map(Number),lat=coordinates[0],lon=coordinates[1],magnitude=Number(quake.Magnitude||0);if(!Number.isFinite(lat)||!Number.isFinite(lon))return[];return[enrich({id:`bmkg-${textId(quake.DateTime||quake.Jam)}`,type:'tsunami',title:'Potenziale tsunami — BMKG Indonesia',place:quake.Wilayah||'Indonesia e mari circostanti',date:quake.DateTime||new Date().toISOString(),lat,lon,severityScore:magnitude>=7.5?94:magnitude>=7?84:72,metricLabel:'Magnitudo',metricValue:`M ${magnitude.toFixed(1)}`,secondaryLabel:'Profondità',secondaryValue:quake.Kedalaman||'Non indicata',probability:null,probabilityNote:'BMKG pubblica una valutazione testuale del potenziale tsunami, non una percentuale.',description:potential,source:'BMKG Indonesia',sourceUrl:'https://data.bmkg.go.id/gempabumi/',officialLevel:potential})]
}

async function loadAll(force=false){
 $('#mapStatus').className='map-status';$('#mapStatus span').textContent='Aggiornamento degli eventi reali…';$('#eventList').innerHTML='<div class="event-loading"><i></i><b>Raccolgo gli eventi</b><p>Interrogo USGS, NASA EONET e i centri tsunami.</p></div>';$('#sourceNotices').innerHTML='';
 const sources=[['USGS',loadEarthquakes],['NASA EONET',loadEonet],['NOAA Tsunami CAP',loadTsunami],['JMA Tsunami',loadJmaTsunami],['BMKG Indonesia',loadBmkgTsunami]],results=await Promise.allSettled(sources.map(([,loader])=>loader(force)));sourceState={};events=[];results.forEach((result,index)=>{sourceState[sources[index][0]]=result.status==='fulfilled';if(result.status==='fulfilled')events.push(...result.value)});
 events=[...new Map(events.map(event=>[event.id,event])).values()];renderSourceState();renderAll();const working=Object.values(sourceState).filter(Boolean).length;
 lastWorldRefresh=Date.now();$('#mapStatus').className=`map-status ${working?'ready':'error'}`;$('#mapStatus span').textContent=working?`${events.length} eventi ricevuti da ${working} fonti`:'Fonti momentaneamente non raggiungibili';$('#worldUpdated').textContent=new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});$('#sourceHealth').textContent=`${working} fonti su ${Object.keys(sourceState).length} disponibili`;if(!requestedEventHandled){requestedEventHandled=true;const requested=new URLSearchParams(location.search).get('event');if(requested&&events.some(event=>event.id===requested)){openDetail(requested);history.replaceState({},'',location.pathname)}}
}
function renderSourceState(){const failed=Object.entries(sourceState).filter(([,ok])=>!ok).map(([name])=>name);$('#sourceNotices').innerHTML=failed.map(name=>`<div class="source-notice">${esc(name)} non raggiungibile: le altre fonti restano attive.</div>`).join('')}
function filteredEvents(){const cutoff={day:864e5,week:7*864e5,month:30*864e5}[activePeriod],now=Date.now();return events.filter(event=>(activeType==='all'||event.type===activeType)&&now-new Date(event.date).getTime()<=cutoff).sort(sortEvents)}
function sortEvents(a,b){const mode=$('#sortSelect').value;if(mode==='recent')return new Date(b.date)-new Date(a.date);if(mode==='severity')return b.severityScore-a.severityScore;if(mode==='distance')return a.distance-b.distance;return(b.impact+b.severityScore*.25)-(a.impact+a.severityScore*.25)}
function renderAll(){events.forEach(enrich);const visible=filteredEvents();renderMarkers(visible);renderList(visible);renderStats(visible);evaluateWatchLocations()}
function markerIcon(event){const size=Math.round(24+event.severityScore/8);return L.divIcon({className:'',html:`<div class="event-marker ${event.level}" style="width:${size}px;height:${size}px">${typeInfo[event.type].icon}</div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
function renderMarkers(list){eventLayer.clearLayers();list.slice().sort((a,b)=>b.severityScore-a.severityScore).slice(0,350).forEach(event=>{const marker=L.marker([event.lat,event.lon],{icon:markerIcon(event)}).bindTooltip(`<b>${esc(event.title)}</b><br>${esc(event.metricValue)} • ${formatDistance(event.distance)} da ${esc(referencePlace.name)}`);marker.on('click',()=>openDetail(event.id));marker.addTo(eventLayer)})}
function renderList(list){$('#eventList').innerHTML=list.length?list.slice(0,200).map(event=>`<button class="event-card ${event.id===activeEventId?'active':''}" data-event-id="${esc(event.id)}"><span class="event-symbol ${event.level}">${typeInfo[event.type].icon}</span><div><span>${typeInfo[event.type].label} • ${severityLabels[event.level]}</span><b>${esc(event.title)}</b><small>${relativeTime(event.date)} • ${formatDistance(event.distance)}</small></div><div class="event-impact"><strong>${event.impact}</strong><em>impatto AI</em></div></button>`).join(''):'<div class="event-empty"><b>Nessun evento con questi filtri</b><p>Prova un periodo più ampio oppure seleziona “Tutti”.</p></div>';$$('[data-event-id]').forEach(button=>button.onclick=()=>openDetail(button.dataset.eventId))}
function renderStats(list){$('#visibleCount').textContent=list.length;$('#criticalCount').textContent=list.filter(event=>['high','extreme'].includes(event.level)).length;const nearest=[...list].sort((a,b)=>a.distance-b.distance)[0];$('#nearestEvent').textContent=nearest?typeInfo[nearest.type].label:'--';$('#nearestDistance').textContent=nearest?`${formatDistance(nearest.distance)} da ${referencePlace.name}`:'Nessun evento visibile'}
function impactText(event){if(event.impact>=70)return`L’evento è relativamente vicino o intenso rispetto a ${referencePlace.name}. Segui con attenzione gli aggiornamenti ufficiali e le indicazioni delle autorità.`;if(event.impact>=40)return`L’evento merita attenzione rispetto a ${referencePlace.name}, ma l’indice non equivale a un’allerta né dimostra conseguenze certe.`;if(event.impact>=15)return`L’impatto orientativo su ${referencePlace.name} risulta limitato, soprattutto per distanza o intensità. Continua a verificare gli aggiornamenti se devi viaggiare nell’area.`;return`La grande distanza da ${referencePlace.name} riduce fortemente la rilevanza diretta stimata. L’evento resta importante per l’area in cui si trova.`}
function openDetail(id){const event=events.find(item=>item.id===id);if(!event)return;activeEventId=id;renderList(filteredEvents());const probability=event.probability?`<div class="probability-value">${esc(event.probability)}</div><p>${esc(event.probabilityNote)}</p>`:`<div class="probability-unavailable"><b>Percentuale non disponibile</b><p>${esc(event.probabilityNote)}</p></div>`;$('#eventDetailContent').innerHTML=`<div class="detail-hero"><span class="detail-type">${typeInfo[event.type].label.toUpperCase()} • ${esc(event.source)}</span><h2>${esc(event.title)}</h2><p class="detail-place">${esc(event.place)}</p><span class="detail-level ${event.level}">Criticità ${severityLabels[event.level]}</span></div><div class="impact-panel"><div class="impact-score"><strong>${event.impact}</strong><span>/100</span></div><div><small>IMPATTO AI SU ${esc(referencePlace.name).toUpperCase()}</small><b>${event.impact>=70?'Rilevanza elevata':event.impact>=40?'Da seguire':event.impact>=15?'Rilevanza limitata':'Rilevanza molto bassa'}</b><p>Indice orientativo, non probabilità né allerta ufficiale.</p></div></div><div class="detail-grid"><div><span>${esc(event.metricLabel)}</span><b>${esc(event.metricValue)}</b></div><div><span>${esc(event.secondaryLabel)}</span><b>${esc(event.secondaryValue)}</b></div><div><span>Distanza</span><b>${formatDistance(event.distance)}</b></div><div><span>Aggiornamento</span><b>${relativeTime(event.date)}</b></div></div><section class="detail-section"><span>LETTURA METEO AI</span><h3>Cosa significa per la tua località</h3><p>${esc(impactText(event))}</p></section><section class="detail-section"><span>EVENTO OSSERVATO</span><h3>Informazioni disponibili</h3><p>${esc(event.description)}</p></section><section class="detail-section"><span>PROBABILITÀ O CERTEZZA UFFICIALE</span><h3>Nessuna percentuale inventata</h3>${probability}</section><section class="detail-section"><span>LIVELLO DELLA FONTE</span><h3>${esc(event.officialLevel)}</h3><p>La terminologia appartiene alla fonte indicata e può avere significati diversi secondo il tipo di evento.</p></section><a class="detail-source" href="${esc(safeUrl(event.sourceUrl))}" target="_blank" rel="noopener">Apri la fonte ufficiale ↗</a>`;$('#eventDetail').classList.add('open');$('#detailOverlay').classList.add('open');$('#eventDetail').setAttribute('aria-hidden','false')}
function closeDetail(){activeEventId='';$('#eventDetail').classList.remove('open');$('#detailOverlay').classList.remove('open');$('#eventDetail').setAttribute('aria-hidden','true');renderList(filteredEvents())}

async function searchPlaces(query){const params=new URLSearchParams({name:query,count:6,language:'it',format:'json'}),response=await fetchResilient(`https://geocoding-api.open-meteo.com/v1/search?${params}`);if(!response.ok)throw Error();return(await response.json()).results||[]}
let searchTimer;$('#worldLocationInput').oninput=()=>{clearTimeout(searchTimer);const query=$('#worldLocationInput').value.trim();if(query.length<2){$('#worldSuggestions').innerHTML='';return}searchTimer=setTimeout(async()=>{try{const places=await searchPlaces(query);$('#worldSuggestions').innerHTML=places.map((place,index)=>`<button type="button" data-place-index="${index}"><b>${esc(place.name)}</b><small>${esc([place.admin1,place.country].filter(Boolean).join(', '))}</small></button>`).join('');$$('[data-place-index]').forEach(button=>button.onclick=()=>selectPlace(places[Number(button.dataset.placeIndex)]))}catch(_){$('#worldSuggestions').innerHTML=''}},250)};
function selectPlace(place){referencePlace={name:place.name,country:place.country,country_code:place.country_code,admin1:place.admin1,latitude:Number(place.latitude),longitude:Number(place.longitude)};try{localStorage.setItem('meteo-current-place',JSON.stringify(referencePlace))}catch(_){}$('#worldLocationInput').value='';$('#worldSuggestions').innerHTML='';renderReferenceMarker();events.forEach(enrich);renderAll();worldMap.flyTo([referencePlace.latitude,referencePlace.longitude],5,{duration:.8})}
$('#worldLocationForm').onsubmit=async event=>{event.preventDefault();const query=$('#worldLocationInput').value.trim();if(!query)return;try{const places=await searchPlaces(query);if(places[0])selectPlace(places[0])}catch(_){$('#worldSuggestions').innerHTML='<button type="button"><b>Località non trovata</b><small>Controlla il nome e riprova.</small></button>'}};

const severityRank={low:0,moderate:1,high:2,extreme:3};
function loadWatchLocations(){try{const stored=JSON.parse(localStorage.getItem('meteo-watch-locations')||'[]');watchLocations=Array.isArray(stored)?stored.filter(rule=>Number.isFinite(Number(rule.latitude))&&Number.isFinite(Number(rule.longitude))).slice(0,20):[]}catch(_){watchLocations=[]}renderWatchList();updateNotificationStatus()}
function saveWatchLocations(){try{localStorage.setItem('meteo-watch-locations',JSON.stringify(watchLocations))}catch(_){}renderWatchList();evaluateWatchLocations()}
function watchTypeLabel(type){return type==='all'?'Tutti gli eventi':typeInfo[type]?.label||'Eventi'}
function renderWatchList(){$('#watchCount').textContent=watchLocations.length;$('#watchListCount').textContent=`${watchLocations.length} ${watchLocations.length===1?'località':'località'}`;$('#watchList').innerHTML=watchLocations.length?watchLocations.map(rule=>`<div class="watch-rule"><div><b>${esc(rule.name)}</b><small>${watchTypeLabel(rule.type)} • ${Number(rule.radius).toLocaleString('it-IT')} km • da criticità ${severityLabels[rule.minLevel].toLowerCase()}</small></div><button data-remove-watch="${esc(rule.id)}" aria-label="Rimuovi ${esc(rule.name)}">×</button></div>`).join(''):'<div class="watch-empty"><b>Nessuna località sorvegliata</b><p>Aggiungi una città oppure usa la posizione del dispositivo.</p></div>';$$('[data-remove-watch]').forEach(button=>button.onclick=()=>{watchLocations=watchLocations.filter(rule=>rule.id!==button.dataset.removeWatch);saveWatchLocations()})}
function watchMatches(){const cutoff=Date.now()-7*864e5,matches=[];watchLocations.forEach(rule=>events.forEach(event=>{if(new Date(event.date).getTime()<cutoff)return;if(rule.type!=='all'&&rule.type!==event.type)return;if(severityRank[event.level]<severityRank[rule.minLevel])return;const distance=distanceKm(rule.latitude,rule.longitude,event.lat,event.lon);if(distance<=Number(rule.radius))matches.push({rule,event,distance})}));return matches.sort((a,b)=>b.event.severityScore-a.event.severityScore||a.distance-b.distance)}
function evaluateWatchLocations(){const matches=watchMatches();$('#watchAlerts').classList.toggle('hidden',!matches.length);$('#watchAlertList').innerHTML=matches.slice(0,20).map(match=>`<button class="watch-alert-card" data-watch-event="${esc(match.event.id)}"><i>${typeInfo[match.event.type].icon}</i><div><b>${esc(match.event.title)}</b><small>${esc(match.rule.name)} • ${formatDistance(match.distance)} • criticità ${severityLabels[match.event.level].toLowerCase()}</small></div></button>`).join('');$$('[data-watch-event]').forEach(button=>button.onclick=()=>openDetail(button.dataset.watchEvent));sendWatchNotifications(matches)}
function updateNotificationStatus(){const button=$('#enableNotifications');if(!('Notification'in window)){$('#notificationStatus').textContent='Non supportate da questo browser.';button.disabled=true;return}const status=Notification.permission;if(status==='granted'){$('#notificationStatus').textContent='Attive: gli avvisi vengono mostrati durante gli aggiornamenti.';button.textContent='Notifiche attive';button.disabled=true}else if(status==='denied'){$('#notificationStatus').textContent='Bloccate nelle impostazioni del browser.';button.textContent='Notifiche bloccate';button.disabled=true}else{$('#notificationStatus').textContent='Serve il tuo consenso; nessuna autorizzazione viene chiesta automaticamente.';button.textContent='Attiva notifiche';button.disabled=false}}
async function requestNotifications(){if(!('Notification'in window))return;try{await Notification.requestPermission()}catch(_){}updateNotificationStatus();if(Notification.permission==='granted')sendWatchNotifications(watchMatches())}
async function sendWatchNotifications(matches){if(!('Notification'in window)||Notification.permission!=='granted')return;let notified={};try{notified=JSON.parse(localStorage.getItem('meteo-notified-events')||'{}')||{}}catch(_){}const now=Date.now();Object.keys(notified).forEach(key=>{if(now-Number(notified[key])>30*864e5)delete notified[key]});const fresh=matches.filter(match=>now-new Date(match.event.date).getTime()<=864e5&&!notified[`${match.rule.id}:${match.event.id}`]).slice(0,3);for(const match of fresh){const key=`${match.rule.id}:${match.event.id}`,title=`${typeInfo[match.event.type].label} vicino a ${match.rule.name}`,options={body:`${match.event.title} • ${formatDistance(match.distance)} • criticità ${severityLabels[match.event.level]}`,icon:'icon.svg',badge:'icon.svg',tag:key,data:{url:`world-live.html?event=${encodeURIComponent(match.event.id)}`}};try{const registration='serviceWorker'in navigator?await navigator.serviceWorker.getRegistration():null;if(registration)await registration.showNotification(title,options);else new Notification(title,options);notified[key]=now}catch(_){}}try{localStorage.setItem('meteo-notified-events',JSON.stringify(notified))}catch(_){}}
function openWatchDrawer(){$('#watchDrawer').classList.add('open');$('#watchOverlay').classList.add('open');$('#watchDrawer').setAttribute('aria-hidden','false');updateNotificationStatus()}
function closeWatchDrawer(){$('#watchDrawer').classList.remove('open');$('#watchOverlay').classList.remove('open');$('#watchDrawer').setAttribute('aria-hidden','true');$('#watchSuggestions').innerHTML=''}
function setPendingWatch(place){pendingWatchPlace={name:place.name,country:place.country||'',latitude:Number(place.latitude),longitude:Number(place.longitude)};$('#watchPlaceInput').value=placeLabel(place);$('#watchSuggestions').innerHTML=''}
let watchSearchTimer;$('#watchPlaceInput').oninput=()=>{pendingWatchPlace=null;clearTimeout(watchSearchTimer);const query=$('#watchPlaceInput').value.trim();if(query.length<2){$('#watchSuggestions').innerHTML='';return}watchSearchTimer=setTimeout(async()=>{try{const places=await searchPlaces(query);$('#watchSuggestions').innerHTML=places.map((place,index)=>`<button type="button" data-watch-place="${index}"><b>${esc(place.name)}</b><small>${esc([place.admin1,place.country].filter(Boolean).join(', '))}</small></button>`).join('');$$('[data-watch-place]').forEach(button=>button.onclick=()=>setPendingWatch(places[Number(button.dataset.watchPlace)]))}catch(_){$('#watchSuggestions').innerHTML=''}},250)};
$('#watchForm').onsubmit=async event=>{event.preventDefault();if(!pendingWatchPlace){const places=await searchPlaces($('#watchPlaceInput').value.trim()).catch(()=>[]);if(!places[0])return;setPendingWatch(places[0])}const rule={id:`watch-${Date.now()}-${textId(pendingWatchPlace.name)}`,name:pendingWatchPlace.name,country:pendingWatchPlace.country,latitude:pendingWatchPlace.latitude,longitude:pendingWatchPlace.longitude,radius:Number($('#watchRadius').value),minLevel:$('#watchSeverity').value,type:$('#watchType').value};if(!watchLocations.some(item=>item.name===rule.name&&item.type===rule.type&&item.radius===rule.radius))watchLocations.push(rule);pendingWatchPlace=null;$('#watchPlaceInput').value='';saveWatchLocations()};
$('#watchCurrentPlace').onclick=()=>setPendingWatch(referencePlace);$('#watchGeolocation').onclick=()=>{if(!navigator.geolocation){$('#notificationStatus').textContent='Geolocalizzazione non supportata.';return}$('#watchGeolocation').disabled=true;navigator.geolocation.getCurrentPosition(position=>{setPendingWatch({name:'Posizione dispositivo',country:'',latitude:position.coords.latitude,longitude:position.coords.longitude});$('#watchGeolocation').disabled=false},()=>{$('#notificationStatus').textContent='Posizione non disponibile o autorizzazione negata.';$('#watchGeolocation').disabled=false},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})};

$$('[data-event-type]').forEach(button=>button.onclick=()=>{$$('[data-event-type]').forEach(item=>item.classList.toggle('active',item===button));activeType=button.dataset.eventType;renderAll()});
$('#periodSelect').onchange=()=>{activePeriod=$('#periodSelect').value;loadAll(false)};$('#sortSelect').onchange=renderAll;$('#refreshWorldBtn').onclick=()=>loadAll(true);$('#nearMeBtn').onclick=()=>worldMap.flyTo([referencePlace.latitude,referencePlace.longitude],6,{duration:.8});$('#detailClose').onclick=closeDetail;$('#detailOverlay').onclick=closeDetail;$('#watchBtn').onclick=openWatchDrawer;$('#openWatchAlerts').onclick=openWatchDrawer;$('#watchClose').onclick=closeWatchDrawer;$('#watchOverlay').onclick=closeWatchDrawer;$('#enableNotifications').onclick=requestNotifications;document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeDetail();closeWatchDrawer()}});
$('#worldThemeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('meteo-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('meteo-theme')==='dark')document.body.classList.add('dark');
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
initMap();renderReferenceMarker();loadWatchLocations();loadAll(false);setInterval(()=>{if(!document.hidden)loadAll(false)},600000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-lastWorldRefresh>600000)loadAll(false)});

